---
title: "Plot study visits - Preschool MRS"
author: "Meaghan Perdue"
date: "2022-01-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = '/Users/meaghan/OneDrive - University of Calgary/Preschool_data/MRS/data/')
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(viridis)
```

## Plot participant ages/timepoints
using viridis color package for colorblind accessibility
```{r}
#read in data
acg_dat <- read.csv("/Users/meaghan/OneDrive - University of Calgary/Preschool_data/MRS/data/acg_data_molal_outliers_removed_n112_tissuefraction.csv")

lag_dat<-read.csv("/Users/meaghan/OneDrive - University of Calgary/Preschool_data/MRS/data/lag_data_molal_outliers_removed_n319_tissuefraction.csv")

#filter by age at 1st MRI session (1 row/subject), order by age at first session
acg_age_ses1 <- acg_dat %>% 
  group_by(subj_id) %>%
  filter(mri_age_y == min(mri_age_y)) %>% 
  arrange(mri_age_y)
#create subject ID variable by order of age at first MRI
acg_age_ses1$id_by_age_ses1 <- seq.int(nrow(acg_age_ses1))

#select only subj_id and acg_age_ses1 columns to create index of subjects ordered by age of first scan
acg_subj_id_age_index <- acg_age_ses1 %>%
  dplyr::select(subj_id, id_by_age_ses1)

#join index df to acg_dat
acg_dat_age_index<-left_join(acg_dat, acg_subj_id_age_index, by = "subj_id")

p1<-ggplot(acg_dat_age_index, aes(x=mri_age_y, y=id_by_age_ses1, color=as.factor(female)))

plot_acg_sessions<-p1 + 
  geom_point(size=.5) +
  geom_line(aes(group = as.factor(id_by_age_ses1))) +
  labs(title = "Anterior Cingulate Cortex", x = "Age (years)", y = "Participant") +
  scale_x_continuous(limits = c(1, 12), n.breaks = 11) +
  scale_y_continuous(limits = c(1,102), expand = c(.01, .01)) +
  scale_color_viridis(name = "Sex", labels = c("Male", "Female"), discrete = TRUE, option = "H", begin = .2, end = .8) +
  theme_classic() +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), legend.position = c(.8,.2))
plot_acg_sessions
ggsave("/Users/meaghan/OneDrive - University of Calgary/Preschool_data/MRS/results/acg_timepoints_n112.png", plot=plot_acg_sessions)

#LAG
#filter by age at 1st MRI session (1 row/subject), order by age at first session
lag_age_ses1 <- lag_dat %>% 
  group_by(subj_id) %>%
  filter(mri_age_y == min(mri_age_y)) %>% 
  arrange(mri_age_y)
#create subject ID variable by order of age at first MRI
lag_age_ses1$id_by_age_ses1 <- seq.int(nrow(lag_age_ses1))

#select only subj_id and lag_age_ses1 columns to create index of subjects ordered by age of first scan
lag_subj_id_age_index <- lag_age_ses1 %>%
  dplyr::select(subj_id, id_by_age_ses1)

#join index df to lag_dat
lag_dat_age_index<-left_join(lag_dat, lag_subj_id_age_index, by = "subj_id")

p2<-ggplot(lag_dat_age_index, aes(x=mri_age_y, y=id_by_age_ses1, color=as.factor(female)))

plot_lag_sessions<-p2 + 
  geom_point(size=.5) +
  geom_line(aes(group = as.factor(id_by_age_ses1))) +
  labs(title = "Left Temporo-Parietal Region", x = "Age (years)", y = "Participant") +
  scale_x_continuous(limits = c(1, 12), n.breaks = 11) +
  scale_y_continuous(limits = c(1,102), expand = c(.01, .01)) +
  scale_color_viridis(name = "Sex", labels = c("Male", "Female"), discrete = TRUE, option = "H", begin = .2, end = .8) +
  theme_classic() +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), legend.position = "none")
plot_lag_sessions
ggsave("/Users/meaghan/OneDrive - University of Calgary/Preschool_data/MRS/results/lag_timepoints_n319.png", plot = plot_lag_sessions)

#combine into a single figure
session_fig<-plot_acg_sessions + plot_lag_sessions + plot_layout(nrow=1)
session_fig
ggsave("/Users/meaghan/OneDrive - University of Calgary/Preschool_data/MRS/manuscript/figures/session_timepoints_fig_updated.png", plot=session_fig, width = 6.5, height = 6.5, units = "in")

```




